Feature/character movement
hawkjstn98/OTProject pull request #2
Opened 2019-09-27 12:25 UTC by Handriki

Penambahan Script :
- Control Character
- Control Camera(masih Horizontal)

2019-09-27 17:08 UTC, hawkjstn98 approved these changes

2019-09-27 17:08 UTC, hawkjstn98 commented on Assets/PlayerController.cs
> +    public float gravityScale = 1.0f;
Pindahin ke Constant ya beb

2019-09-27 17:08 UTC, hawkjstn98 commented on Assets/PlayerController.cs
> +    public static float globalGravity = -9.81f;
Ini juga pindahin aja beb ke constant

2019-09-27 17:09 UTC, hawkjstn98 approved these changes

2019-09-28 08:56 UTC, yoshihio requested changes

2019-09-28 08:56 UTC, frapslover63 commented on Assets/PlayerController.cs
> +        if(other.gameObject.name == "Cube"){
Change to check for tags instead

2019-09-28 09:27 UTC, hawkjstn98 approved these changes

2019-09-28 13:58 UTC, merged